version: "3"

services:
  backend-app:
    container_name: backend-api
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - backend-app
    ports:
      - 3000:3000
  